version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app:cached
      - /usr/src/app/node_modules
    ports:
      - '3001:3001'
    depends_on:
      - db

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web:/usr/src/app:cached
      - /usr/src/app/node_modules
    ports:
      - '3002:3000'
    depends_on:
      - server

  db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    volumes:
      - ./proxy/cert:/etc/nginx/certificates
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - server
      - web

volumes:
  db_data:
