version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile-dev
    volumes:
      - ./server:/usr/src/app:cached
      - /usr/src/app/node_modules
    ports:
      - '3001:3000'
    depends_on:
      - db
    command: pnpm run start:dev

  web:
    build:
      context: ./web
      dockerfile: Dockerfile-dev
    volumes:
      - ./web:/usr/src/app:cached
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - server

  db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
