# Dockerfile for NestJS app

FROM node:18-alpine

# Install pnpm
RUN npm install -g pnpm

WORKDIR /usr/src/app

# Install dependencies
COPY pnpm-lock.yaml ./
COPY package.json ./
RUN pnpm install

# Copy the rest of the application code
COPY . .

# Expose the application port
EXPOSE 3001

# Command to run the application in development mode with hot reload
CMD ["pnpm", "run", "start:dev"]
